import type { Lang } from './translations';
export type Localized = Record<Lang,string>;
export type Artwork = {asset:string;caption:Localized};
export type Project = {slug:string;name:Localized;category:Localized;industry:Localized;overview:Localized;direction:Localized;scope:Record<Lang,string[]>;cover:string;theme:string;gallery:Artwork[]};
const same=(s:string):Localized=>({en:s,tr:s,ar:s});
const l=(en:string,tr:string,ar:string):Localized=>({en,tr,ar});
export const projects:Project[]=[
 {
  slug:'athar-perfumes',name:same('ATHAR PERFUMES'),category:l('Brand identity · Packaging','Marka kimliği · Ambalaj','هوية بصرية · تغليف'),industry:l('Perfumery','Parfüm','العطور'),cover:'athar-perfume',theme:'athar',
  overview:l('A complete visual identity for Athar Perfumes, bringing together an Arabic-inspired logo, brand patterns, packaging, shopping bags, business cards, and branded applications.','Athar Perfumes için Arap estetiğinden ilham alan bir logo, marka desenleri, ambalaj, alışveriş çantaları, kartvizitler ve marka uygulamalarını bir araya getiren kapsamlı bir görsel kimlik.','هوية بصرية متكاملة لعطور أثر، تجمع شعارًا مستلهمًا من التفاصيل العربية مع أنماط العلامة التجارية والتغليف وأكياس التسوق وبطاقات الأعمال وتطبيقات متنوعة.'),
  direction:l('Elegance and Arabic-inspired details meet in a refined palette. The logo and repeating graphic elements connect the packaging to the wider identity.','Zarafet ve Arap estetiğinden ilham alan detaylar, özenli bir renk paletinde buluşuyor. Logo ve tekrarlanan grafik öğeler, ambalajı genel marka kimliğine bağlıyor.','تلتقي الأناقة والتفاصيل المستلهمة من الطابع العربي في لوحة ألوان راقية. ويربط الشعار والعناصر البصرية المتكررة بين التغليف وبقية تطبيقات الهوية.'),
  scope:{en:['Logo design','Visual identity','Brand patterns','Packaging','Business cards','Shopping bags'],tr:['Logo tasarımı','Görsel kimlik','Marka desenleri','Ambalaj','Kartvizit','Alışveriş çantaları'],ar:['تصميم الشعار','الهوية البصرية','أنماط العلامة','التغليف','بطاقات الأعمال','أكياس التسوق']},
  gallery:[{asset:'athar-logo',caption:l('The ATHAR identity','ATHAR kimliği','هوية أثر')},{asset:'athar-pattern',caption:l('Brand pattern','Marka deseni','نمط العلامة التجارية')},{asset:'athar-bag',caption:l('Shopping bag application','Alışveriş çantası uygulaması','تطبيق الهوية على أكياس التسوق')},{asset:'athar-cards',caption:l('Business card applications','Kartvizit uygulamaları','تطبيقات بطاقات الأعمال')},{asset:'athar-packaging',caption:l('Packaging artwork','Ambalaj tasarımı','تصميم العبوة')}]
 },
 {
  slug:'troy-41',name:same('TROY 41 REAL ESTATE'),category:l('Brand identity · Social media','Marka kimliği · Sosyal medya','هوية بصرية · تواصل اجتماعي'),industry:l('Real estate · Türkiye','Gayrimenkul · Türkiye','العقارات · تركيا'),cover:'troy-sign',theme:'troy',
  overview:l('Brand identity applications and social media communication for Troy 41 Real Estate. The project spans the company logo, corporate applications, and property advertising.','Troy 41 Real Estate için marka kimliği uygulamaları ve sosyal medya iletişimi. Proje, şirket logosunu, kurumsal uygulamaları ve gayrimenkul reklamlarını kapsıyor.','هوية بصرية وتطبيقات مؤسسية وتصاميم للتواصل الاجتماعي لصالح Troy 41 Real Estate. يشمل المشروع شعار الشركة وتطبيقات الهوية والإعلانات العقارية.'),
  direction:l('A consistent, professional visual language connects the brand’s digital advertising with its printed and physical applications.','Tutarlı ve profesyonel bir görsel dil, markanın dijital reklamlarını basılı ve fiziksel uygulamalarıyla birleştiriyor.','لغة بصرية متناسقة واحترافية تربط إعلانات العلامة الرقمية بتطبيقاتها المطبوعة والمادية.'),
  scope:{en:['Logo design','Corporate identity','Social media design','Property advertising'],tr:['Logo tasarımı','Kurumsal kimlik','Sosyal medya tasarımı','Gayrimenkul reklamları'],ar:['تصميم الشعار','الهوية المؤسسية','تصاميم التواصل الاجتماعي','الإعلانات العقارية']},
  gallery:[{asset:'troy-hero',caption:l('Property advertising','Gayrimenkul reklamı','إعلان عقاري')},{asset:'troy-cards',caption:l('Corporate stationery','Kurumsal materyaller','مطبوعات الهوية المؤسسية')},{asset:'troy-investment',caption:l('Real estate investment post','Gayrimenkul yatırımı gönderisi','منشور الاستثمار العقاري')},{asset:'troy-villa',caption:l('Property promotion','Gayrimenkul tanıtımı','الترويج للعقارات')},{asset:'troy-workers',caption:l('Social media occasion design','Özel gün sosyal medya tasarımı','تصميم مناسبة للتواصل الاجتماعي')}]
 },
 {
  slug:'prime-haven',name:same('PRIME HAVEN REAL ESTATE'),category:l('Social media · Advertising','Sosyal medya · Reklam','تواصل اجتماعي · إعلانات'),industry:l('Real estate · Türkiye','Gayrimenkul · Türkiye','العقارات · تركيا'),cover:'prime-hero',theme:'prime',
  overview:l('Social media design for Prime Haven Real Estate, focused on real estate investment and property opportunities in Türkiye.','Prime Haven Real Estate için Türkiye’deki gayrimenkul yatırımlarına ve konut fırsatlarına odaklanan sosyal medya tasarımları.','تصاميم تواصل اجتماعي لـPrime Haven Real Estate تركز على الاستثمار العقاري والفرص السكنية في تركيا.'),
  direction:l('Premium property imagery, clean typography, and clear marketing messages create a professional and trustworthy presence.','Nitelikli gayrimenkul görselleri, sade tipografi ve açık pazarlama mesajları, profesyonel ve güven veren bir görünüm oluşturuyor.','صور عقارية راقية وخطوط واضحة ورسائل تسويقية مباشرة تعزز حضورًا احترافيًا يبعث على الثقة.'),
  scope:{en:['Social media design','Property marketing','Real estate advertising'],tr:['Sosyal medya tasarımı','Gayrimenkul pazarlaması','Emlak reklamları'],ar:['تصاميم التواصل الاجتماعي','التسويق العقاري','الإعلانات العقارية']},
  gallery:[{asset:'prime-lifestyle',caption:l('A new life in İstanbul','İstanbul’da yeni bir yaşam','حياة جديدة في إسطنبول')},{asset:'prime-investment',caption:l('Investment opportunity','Yatırım fırsatı','فرصة استثمارية')},{asset:'prime-seaview',caption:l('Coastal living','Deniz manzaralı yaşam','إطلالات بحرية')},{asset:'prime-location',caption:l('Investment in Türkiye','Türkiye’de yatırım','الاستثمار في تركيا')},{asset:'prime-returns',caption:l('Property marketing visual','Gayrimenkul pazarlama görseli','تصميم للتسويق العقاري')}]
 },
 {
  slug:'advertising-social',name:l('Advertising & Social Media','Reklam ve Sosyal Medya','الإعلانات والتواصل الاجتماعي'),category:l('Digital campaigns · Promotional design','Dijital kampanyalar · Tanıtım tasarımı','حملات رقمية · تصاميم ترويجية'),industry:l('Selected commercial work','Seçili ticari çalışmalar','أعمال تجارية مختارة'),cover:'advertising-overview',theme:'selection',
  overview:l('A selection of digital campaigns, promotional designs, and social media visuals across real estate, footwear, watches, and travel.','Gayrimenkul, ayakkabı, saat ve seyahat alanlarında dijital kampanyalar, tanıtım tasarımları ve sosyal medya görsellerinden bir seçki.','مختارات من الحملات الرقمية والتصاميم الترويجية ومنشورات التواصل الاجتماعي في العقارات والأحذية والساعات والسفر.'),
  direction:l('Product imagery and direct promotional messages take the lead, with layouts and colors adapted to each brand.','Ürün görselleri ve doğrudan tanıtım mesajları öne çıkıyor; düzen ve renkler her markaya göre şekilleniyor.','تتصدر صور المنتجات والرسائل الترويجية الواضحة التصاميم، مع تنسيق وألوان تناسب كل علامة.'),
  scope:{en:['Social media','Digital advertising','Promotional design'],tr:['Sosyal medya','Dijital reklam','Tanıtım tasarımı'],ar:['التواصل الاجتماعي','الإعلانات الرقمية','التصاميم الترويجية']},
  gallery:[{asset:'advertising-overview',caption:l('Selected advertising and social media designs','Seçili reklam ve sosyal medya tasarımları','مختارات من الإعلانات وتصاميم التواصل الاجتماعي')}]
 },
 {
  slug:'print-outdoor',name:l('Print & Outdoor','Baskı ve Açık Hava','المطبوعات والإعلانات الخارجية'),category:l('Outdoor advertising · Print','Açık hava reklamı · Baskı','إعلانات خارجية · مطبوعات'),industry:l('Selected commercial work','Seçili ticari çalışmalar','أعمال تجارية مختارة'),cover:'nova-billboard',theme:'outdoor',
  overview:l('Selected large-format and print applications, including NOVA footwear billboards and street advertising, roll-ups, signage, and a travel brochure.','NOVA ayakkabı billboard ve sokak reklamları, roll-up’lar, tabela ve seyahat broşürünü içeren büyük format ve basılı uygulamalardan bir seçki.','تطبيقات مختارة للطباعة والإعلان الخارجي، تشمل لوحات NOVA للأحذية وإعلانات الشوارع والرول أب واللافتات وبروشور للسفر.'),
  direction:l('Bold product presentation and clear visual hierarchy carry the designs from printed materials into outdoor settings.','Güçlü ürün sunumu ve açık bir görsel hiyerarşi, tasarımları basılı materyallerden açık hava mecralarına taşıyor.','حضور قوي للمنتج وتسلسل بصري واضح يمنحان التصاميم امتدادًا من المطبوعات إلى المساحات الخارجية.'),
  scope:{en:['Billboards','Street advertising','Roll-ups','Brochures','Signage'],tr:['Billboard','Sokak reklamları','Roll-up','Broşür','Tabela'],ar:['لوحات إعلانية','إعلانات شوارع','رول أب','بروشورات','لافتات']},
  gallery:[{asset:'nova-bus-stop',caption:l('NOVA street advertising mockup','NOVA sokak reklamı mockup’ı','موك أب إعلان NOVA في الشارع')},{asset:'nova-street',caption:l('NOVA outdoor application','NOVA açık hava uygulaması','تطبيق NOVA للإعلان الخارجي')},{asset:'travel-brochure',caption:l('Travel brochure presentation','Seyahat broşürü sunumu','عرض بروشور السفر')},{asset:'outdoor-overview',caption:l('Selected print and outdoor applications','Seçili baskı ve açık hava uygulamaları','تطبيقات مختارة للمطبوعات والإعلان الخارجي')}]
 },
 {
  slug:'brand-print',name:l('Brand & Print Applications','Marka ve Baskı Uygulamaları','تطبيقات الهوية والمطبوعات'),category:l('Logo design · Brand applications','Logo tasarımı · Marka uygulamaları','تصميم شعارات · تطبيقات الهوية'),industry:l('Selected commercial work','Seçili ticari çalışmalar','أعمال تجارية مختارة'),cover:'brand-print-overview',theme:'selection',
  overview:l('Selected logo designs, business cards, packaging, shopping bags, and printed applications from a variety of brands.','Farklı markalar için hazırlanmış logo, kartvizit, ambalaj, alışveriş çantası ve basılı uygulamalardan bir seçki.','مجموعة مختارة من الشعارات وبطاقات الأعمال والتغليف وأكياس التسوق والتطبيقات المطبوعة لعلامات متنوعة.'),
  direction:l('Each application carries its own brand character through typography, color, layout, and material presentation.','Her uygulama; tipografi, renk, düzen ve malzeme sunumuyla kendi markasının karakterini yansıtıyor.','يعكس كل تطبيق شخصية علامته من خلال الخطوط والألوان والتنسيق وطريقة عرض المطبوعات.'),
  scope:{en:['Logo design','Business cards','Packaging','Print applications'],tr:['Logo tasarımı','Kartvizit','Ambalaj','Baskı uygulamaları'],ar:['تصميم الشعارات','بطاقات الأعمال','التغليف','تطبيقات مطبوعة']},
  gallery:[{asset:'brand-print-overview',caption:l('Selected brand and print applications','Seçili marka ve baskı uygulamaları','مختارات من تطبيقات الهوية والمطبوعات')}]
 }
];
