export const languages = ['en', 'tr', 'ar'] as const;
export type Lang = (typeof languages)[number];
export function isLang(value: string): value is Lang { return languages.includes(value as Lang); }
export const copy = {
 en: {
  name:'Mohammed Amin', title:'Graphic Designer',
  nav:{home:'Home',work:'Work',about:'About',services:'Services',experience:'Experience',contact:'Contact'},
  meta:'Mohammed Amin is a graphic designer in İzmit, Türkiye, working across brand identity, advertising, social media, packaging and print design.',
  heroTop:'Independent perspective. Purposeful design.',hero1:'Design with',hero2:'purpose.',intro:'I bring creative ideas and brand needs together through thoughtful identities, compelling campaigns, and considered print design.',
  viewWork:'Explore my work',contactMe:'Let’s talk',download:'Download CV',cvLanguage:'PDF · English',based:'Based in İzmit, Türkiye',available:'Open to work & collaborations',selected:'Selected work',
  workIntro:'A considered selection of identities, campaigns, and print. Different formats. One attention to detail.',allWork:'View all projects',project:'View project',aboutLabel:'A little about me',aboutHeadline:'Creativity, with a clear point of view.',
  aboutIntro:'I’m Mohammed Amin, a Yemeni graphic designer based in İzmit, Türkiye, and a graduate of the Advertising Department at Kocaeli University.',
  aboutText:'With over four years of experience, I create purposeful visual solutions that combine creativity, clear communication, and strong attention to detail. My work spans brand identity, social media, advertising, and print across a variety of industries.',
  aboutLink:'More about me',years:'Years of design experience',disciplines:'Branding / Digital / Print',tools:'My everyday toolkit',spoken:'Languages I work in',languageLevels:['Arabic — Native','Turkish — C1','English — Intermediate'],
  education:'Education',degree:'Bachelor’s Degree in Advertising',university:'Kocaeli University',languageSchool:'Turkish Language Center',certificate:'C1 Level Certificate',
  serviceLabel:'What I do',serviceHeading:'From a first impression to a lasting identity.',serviceIntro:'Visual communication shaped around the brand, the message, and where it needs to be seen.',
  services:[
   {title:'Brand identity & logo design',text:'Distinctive logos, visual identities, brand patterns, and consistent applications across every touchpoint.',tags:'Logos · Visual systems · Corporate identity'},
   {title:'Social media & advertising',text:'Clear, engaging visuals for social media, promotional content, and digital advertising.',tags:'Social media · Campaign visuals · Digital ads'},
   {title:'Print & editorial design',text:'Thoughtful layouts and considered typography for brochures, company profiles, business cards, and printed communications.',tags:'Brochures · Company profiles · Stationery'},
   {title:'Packaging & outdoor design',text:'Brand applications that work in the physical world, from packaging and shopping bags to billboards and large-format print.',tags:'Packaging · Billboards · Outdoor advertising'}],
  experienceLabel:'The experience behind the work',experienceHeading:'A creative path, across brands and formats.',experienceIntro:'Independent projects, in-house design, and visual communication for organizations.',present:'Present',freelance:'Freelance Graphic Designer',media:'Media Officer',union:'Yemen Students Union in Türkiye',
  jobs:['Developing custom graphic design projects, social media content, advertising, and corporate identity materials around client requirements.','Designed the company logo and corporate identity, created more than 30 social media posts, and managed social media accounts.','Designed more than 50 social media posts and prepared reports and invitations for programs and seminars.','Managed social media communication and publishing, and designed materials for organizational promotion and events.','Designed billboards, printed advertising materials, social media content, and advertising visuals tailored to client requirements.'],
  contactHeading:'Good work starts with a conversation.',contactIntro:'Have a project in mind or a design opportunity? I’d be happy to hear from you.',emailLabel:'Email me',phoneLabel:'Call me',connect:'Connect on LinkedIn',location:'Location',
  formTitle:'Tell me what you have in mind.',formNote:'This form prepares an email in your email app. Review it there and send it to me.',nameLabel:'Your name',emailField:'Your email',subject:'Subject',message:'Your message',namePlaceholder:'How should I address you?',emailPlaceholder:'you@example.com',subjectPlaceholder:'A project, an opportunity, an idea…',messagePlaceholder:'A little about what you’re looking for…',send:'Prepare email',
  formReady:'Your email draft is ready. If your email app didn’t open, use the link below or copy your message.',openEmail:'Open email draft',copyMessage:'Copy message',copied:'Message copied.',copyError:'Copy was unavailable. Your message is still in the form above.',
  errors:{name:'Please enter your name.',email:'Please enter a valid email address.',subject:'Please enter a subject.',message:'Please add a message (at least 10 characters).'},
  footerHeadline:'Let’s create something meaningful.',footerText:'Thoughtful design. Clear communication.',copyright:'© Mohammed Amin',menu:'Open navigation',close:'Close',navigation:'Navigation',language:'Website language',skip:'Skip to content',
  overview:'The project',direction:'Visual direction',scope:'Project scope',industry:'Industry',gallery:'Selected applications',nextProject:'Next project',backWork:'All projects',enlarge:'Enlarge image',previousImage:'Previous image',nextImage:'Next image',imageOf:'of',
  notFound:'This page isn’t in the collection.',notFoundText:'The link may have changed. Explore the selected work or return home.',backHome:'Back to home'
 },
 tr: {
  name:'Mohammed Amin',title:'Grafik Tasarımcı',
  nav:{home:'Ana Sayfa',work:'İşler',about:'Hakkımda',services:'Hizmetler',experience:'Deneyim',contact:'İletişim'},
  meta:'İzmit’te yaşayan grafik tasarımcı Mohammed Amin. Marka kimliği, reklam, sosyal medya, ambalaj ve basılı materyal tasarımı çalışmaları.',
  heroTop:'Özgün bir bakış. Anlamlı tasarımlar.',hero1:'Her tasarımın',hero2:'bir amacı var.',intro:'Yaratıcı fikirleri marka ihtiyaçlarıyla buluşturuyor; özenli kimlikler, etkili kampanya görselleri ve basılı tasarımlar hazırlıyorum.',
  viewWork:'İşlerimi keşfedin',contactMe:'Konuşalım',download:'CV’yi indir',cvLanguage:'PDF · İngilizce',based:'İzmit, Türkiye',available:'İş fırsatlarına ve iş birliklerine açığım',selected:'Seçili işler',workIntro:'Marka kimlikleri, kampanya görselleri ve basılı tasarımlardan bir seçki. Farklı mecralar, aynı özen.',allWork:'Tüm projeler',project:'Projeyi incele',aboutLabel:'Kısaca ben',aboutHeadline:'Net bir bakış açısıyla yaratıcılık.',
  aboutIntro:'Ben Mohammed Amin. İzmit’te yaşayan Yemenli bir grafik tasarımcıyım. Kocaeli Üniversitesi Reklamcılık Bölümü mezunuyum.',aboutText:'Dört yılı aşkın deneyimimle yaratıcılığı, açık iletişimi ve detaylara gösterdiğim özeni bir araya getiren görsel çözümler üretiyorum. Farklı sektörlerde marka kimliği, sosyal medya, reklam ve basılı tasarım alanlarında çalışıyorum.',aboutLink:'Beni daha yakından tanıyın',years:'Yılı aşkın tasarım deneyimi',disciplines:'Marka kimliği / Dijital / Baskı',tools:'Kullandığım araçlar',spoken:'Diller',languageLevels:['Arapça — Ana dil','Türkçe — C1','İngilizce — Orta seviye'],
  education:'Eğitim',degree:'Reklamcılık Lisans Derecesi',university:'Kocaeli Üniversitesi',languageSchool:'Türkçe Dil Merkezi',certificate:'C1 Seviye Sertifikası',serviceLabel:'Neler yapıyorum?',serviceHeading:'İlk izlenimden kalıcı bir kimliğe.',serviceIntro:'Markaya, mesaja ve kullanılacağı mecraya göre şekillenen görsel iletişim.',
  services:[
   {title:'Marka kimliği ve logo tasarımı',text:'Özgün logolar, görsel kimlikler, marka desenleri ve tüm temas noktalarında tutarlı uygulamalar.',tags:'Logo · Görsel kimlik · Kurumsal kimlik'},
   {title:'Sosyal medya ve reklam',text:'Sosyal medya, tanıtım içerikleri ve dijital reklamlar için açık ve dikkat çekici görseller.',tags:'Sosyal medya · Kampanya görselleri · Dijital reklam'},
   {title:'Basılı ve editoryal tasarım',text:'Broşürler, şirket profilleri, kartvizitler ve basılı iletişim materyalleri için özenli sayfa düzeni ve tipografi.',tags:'Broşür · Şirket profili · Kurumsal materyaller'},
   {title:'Ambalaj ve açık hava tasarımı',text:'Ambalaj ve alışveriş çantalarından billboard ve büyük format baskılara uzanan marka uygulamaları.',tags:'Ambalaj · Billboard · Açık hava reklamı'}],
  experienceLabel:'İşlerimin arkasındaki deneyim',experienceHeading:'Markalar ve mecralar arasında yaratıcı bir yolculuk.',experienceIntro:'Serbest projeler, kurum içi tasarım ve kuruluşlar için görsel iletişim.',present:'Devam ediyor',freelance:'Serbest Grafik Tasarımcı',media:'Medya Sorumlusu',union:'Türkiye Yemenli Öğrenciler Birliği',
  jobs:['Müşteri ihtiyaçlarına göre özel grafik tasarım projeleri, sosyal medya içerikleri, reklamlar ve kurumsal kimlik materyalleri hazırlıyorum.','Şirketin logosunu ve kurumsal kimliğini tasarladım. 30’dan fazla sosyal medya gönderisi hazırladım ve sosyal medya hesaplarını yönettim.','50’den fazla sosyal medya gönderisi tasarladım; program ve seminerler için rapor ve davetiyeler hazırladım.','Sosyal medya iletişimini ve içerik yayın süreçlerini yönettim; kurumsal tanıtım ve etkinlikler için tasarımlar ürettim.','Müşteri ihtiyaçlarına uygun billboard, basılı reklam materyalleri, sosyal medya içerikleri ve reklam görselleri tasarladım.'],
  contactHeading:'İyi işler bir sohbetle başlar.',contactIntro:'Aklınızda bir proje veya tasarım fırsatı mı var? Sizi dinlemek isterim.',emailLabel:'E-posta gönderin',phoneLabel:'Beni arayın',connect:'LinkedIn’de bağlantı kurun',location:'Konum',formTitle:'Aklınızdakini anlatın.',formNote:'Bu form, e-posta uygulamanızda bir taslak hazırlar. Mesajı orada kontrol ederek bana gönderebilirsiniz.',
  nameLabel:'Adınız',emailField:'E-posta adresiniz',subject:'Konu',message:'Mesajınız',namePlaceholder:'Size nasıl hitap edeyim?',emailPlaceholder:'siz@ornek.com',subjectPlaceholder:'Bir proje, bir fırsat, bir fikir…',messagePlaceholder:'Ne aradığınızı kısaca anlatın…',send:'E-posta hazırla',formReady:'E-posta taslağınız hazır. Uygulamanız açılmadıysa aşağıdaki bağlantıyı kullanabilir veya mesajınızı kopyalayabilirsiniz.',openEmail:'E-posta taslağını aç',copyMessage:'Mesajı kopyala',copied:'Mesaj kopyalandı.',copyError:'Kopyalama kullanılamıyor. Mesajınız yukarıdaki formda duruyor.',
  errors:{name:'Lütfen adınızı yazın.',email:'Lütfen geçerli bir e-posta adresi yazın.',subject:'Lütfen bir konu yazın.',message:'Lütfen en az 10 karakterlik bir mesaj yazın.'},
  footerHeadline:'Birlikte anlamlı işler üretelim.',footerText:'Özenli tasarım. Açık iletişim.',copyright:'© Mohammed Amin',menu:'Menüyü aç',close:'Kapat',navigation:'Gezinme',language:'Site dili',skip:'İçeriğe geç',overview:'Proje hakkında',direction:'Görsel yaklaşım',scope:'Proje kapsamı',industry:'Sektör',gallery:'Seçili uygulamalar',nextProject:'Sonraki proje',backWork:'Tüm projeler',enlarge:'Görseli büyüt',previousImage:'Önceki görsel',nextImage:'Sonraki görsel',imageOf:'/',notFound:'Bu sayfa koleksiyonda bulunmuyor.',notFoundText:'Bağlantı değişmiş olabilir. Seçili işleri inceleyebilir veya ana sayfaya dönebilirsiniz.',backHome:'Ana sayfaya dön'
 },
 ar: {
  name:'محمد أمين',title:'مصمم جرافيك',nav:{home:'الرئيسية',work:'أعمالي',about:'نبذة عني',services:'خدماتي',experience:'الخبرة',contact:'تواصل معي'},meta:'محمد أمين، مصمم جرافيك مقيم في إزميت، تركيا. أعمال في الهوية البصرية والإعلانات والتواصل الاجتماعي والتغليف والمطبوعات.',
  heroTop:'رؤية إبداعية. وتصميم هادف.',hero1:'لكل تصميم',hero2:'غاية وأثر.',intro:'أجمع بين الأفكار الإبداعية واحتياجات العلامة التجارية، لأصمم هويات مدروسة وإعلانات مؤثرة ومطبوعات تهتم بكل تفصيل.',viewWork:'اكتشف أعمالي',contactMe:'لنتحدث',download:'تحميل السيرة الذاتية',cvLanguage:'PDF · بالإنجليزية',based:'إزميت، تركيا',available:'متاح لفرص العمل والتعاون',selected:'أعمال مختارة',workIntro:'مجموعة مختارة من الهويات والإعلانات والمطبوعات. تتنوع الوسائط، ويبقى الاهتمام بالتفاصيل.',allWork:'جميع المشاريع',project:'استعرض المشروع',aboutLabel:'نبذة عني',aboutHeadline:'إبداع ينطلق من رؤية واضحة.',
  aboutIntro:'أنا محمد أمين، مصمم جرافيك يمني مقيم في إزميت، تركيا، وخريج قسم الإعلان في جامعة كوجالي.',aboutText:'بخبرة تزيد على أربع سنوات، أبتكر حلولًا بصرية هادفة تجمع بين الإبداع ووضوح الرسالة والعناية بالتفاصيل. تشمل أعمالي الهوية البصرية والتواصل الاجتماعي والإعلانات والمطبوعات لعلامات تجارية في قطاعات متنوعة.',aboutLink:'تعرّف عليّ أكثر',years:'سنوات من الخبرة في التصميم',disciplines:'هويات بصرية / تصميم رقمي / مطبوعات',tools:'أدواتي اليومية',spoken:'اللغات',languageLevels:['العربية — اللغة الأم','التركية — C1','الإنجليزية — مستوى متوسط'],education:'التعليم',degree:'بكالوريوس في الإعلان',university:'جامعة كوجالي',languageSchool:'مركز اللغة التركية',certificate:'شهادة المستوى C1',
  serviceLabel:'ما أقدمه',serviceHeading:'من الانطباع الأول إلى هوية تبقى.',serviceIntro:'تواصل بصري يراعي العلامة التجارية ورسالتها والوسيط الذي تظهر فيه.',services:[
   {title:'الهوية البصرية وتصميم الشعارات',text:'شعارات مميزة وهويات بصرية وأنماط خاصة بالعلامة التجارية، مع تطبيقات متناسقة في مختلف الاستخدامات.',tags:'شعارات · هوية بصرية · هوية مؤسسية'},
   {title:'التواصل الاجتماعي والإعلانات',text:'تصاميم واضحة وجذابة لمنصات التواصل الاجتماعي والمحتوى الترويجي والإعلانات الرقمية.',tags:'تواصل اجتماعي · تصاميم حملات · إعلانات رقمية'},
   {title:'المطبوعات والتصميم التحريري',text:'تنسيق مدروس وعناية بالخطوط في البروشورات والملفات التعريفية وبطاقات الأعمال ومواد التواصل المطبوعة.',tags:'بروشورات · ملفات تعريفية · مطبوعات مؤسسية'},
   {title:'التغليف والإعلانات الخارجية',text:'تطبيقات للعلامة التجارية في الواقع، من العبوات وأكياس التسوق إلى اللوحات الإعلانية والمطبوعات كبيرة الحجم.',tags:'تغليف · لوحات إعلانية · إعلانات خارجية'}],
  experienceLabel:'الخبرة وراء الأعمال',experienceHeading:'مسيرة إبداعية بين العلامات والوسائط.',experienceIntro:'مشاريع مستقلة وتجارب داخل الشركات وتواصل بصري للمؤسسات.',present:'حتى الآن',freelance:'مصمم جرافيك مستقل',media:'مسؤول إعلامي',union:'اتحاد الطلاب اليمنيين في تركيا',jobs:['تطوير مشاريع تصميم مخصصة، تشمل محتوى التواصل الاجتماعي والإعلانات ومواد الهوية المؤسسية وفق احتياجات العملاء.','تصميم شعار الشركة وهويتها المؤسسية، وإعداد أكثر من 30 منشورًا وإدارة حساباتها على منصات التواصل الاجتماعي.','تصميم أكثر من 50 منشورًا للتواصل الاجتماعي، وإعداد تقارير ودعوات للبرامج والندوات.','إدارة التواصل عبر المنصات الاجتماعية وعمليات نشر المحتوى، وإنتاج تصاميم للتعريف بالاتحاد وفعالياته.','تصميم اللوحات الإعلانية والمطبوعات ومحتوى التواصل الاجتماعي والمواد الدعائية بما يلائم متطلبات العملاء.'],
  contactHeading:'الأعمال الجيدة تبدأ بحوار.',contactIntro:'لديك مشروع أو فرصة عمل في التصميم؟ يسعدني أن أسمع منك.',emailLabel:'راسلني',phoneLabel:'اتصل بي',connect:'تواصل عبر LinkedIn',location:'الموقع',formTitle:'أخبرني بما يدور في بالك.',formNote:'يجهّز هذا النموذج رسالة في تطبيق بريدك الإلكتروني. راجعها هناك ثم أرسلها إليّ.',nameLabel:'اسمك',emailField:'بريدك الإلكتروني',subject:'الموضوع',message:'رسالتك',namePlaceholder:'كيف أناديك؟',emailPlaceholder:'you@example.com',subjectPlaceholder:'مشروع، فرصة، فكرة…',messagePlaceholder:'حدثني قليلًا عما تبحث عنه…',send:'تجهيز الرسالة',formReady:'مسودة رسالتك جاهزة. إذا لم يفتح تطبيق البريد، استخدم الرابط أدناه أو انسخ رسالتك.',openEmail:'فتح مسودة البريد',copyMessage:'نسخ الرسالة',copied:'تم نسخ الرسالة.',copyError:'تعذّر النسخ. لا تزال رسالتك موجودة في النموذج أعلاه.',errors:{name:'يرجى كتابة اسمك.',email:'يرجى كتابة بريد إلكتروني صحيح.',subject:'يرجى كتابة الموضوع.',message:'يرجى كتابة رسالة من 10 أحرف على الأقل.'},footerHeadline:'لنصنع معًا شيئًا ذا معنى.',footerText:'تصميم مدروس. وتواصل واضح.',copyright:'© محمد أمين',menu:'فتح القائمة',close:'إغلاق',navigation:'التنقل',language:'لغة الموقع',skip:'انتقل إلى المحتوى',overview:'عن المشروع',direction:'التوجه البصري',scope:'نطاق المشروع',industry:'القطاع',gallery:'تطبيقات مختارة',nextProject:'المشروع التالي',backWork:'جميع المشاريع',enlarge:'تكبير الصورة',previousImage:'الصورة السابقة',nextImage:'الصورة التالية',imageOf:'من',notFound:'هذه الصفحة ليست ضمن المجموعة.',notFoundText:'ربما تغيّر الرابط. يمكنك استكشاف الأعمال أو العودة إلى الرئيسية.',backHome:'العودة إلى الرئيسية'
 }
};
export const contact = {email:'shrfaldynmhmd355@gmail.com',phone:'+90 531 519 48 95',tel:'+905315194895',linkedin:'https://www.linkedin.com/in/mohammed-amin-612518269',location:'İzmit, Kocaeli, Türkiye'};
