'use client';
import {useState,useRef,type FormEvent} from 'react';
import {ArrowUpRight,Copy} from 'lucide-react';
import {copy,contact,type Lang} from '@/content/translations';
type Field='name'|'email'|'subject'|'message';
export function ContactForm({lang}:{lang:Lang}){
 const t=copy[lang],form=useRef<HTMLFormElement>(null);
 const [errors,setErrors]=useState<Partial<Record<Field,string>>>({}),[draft,setDraft]=useState<{href:string;body:string}|null>(null),[feedback,setFeedback]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const fields=Object.fromEntries(['name','email','subject','message'].map(k=>[k,String(data.get(k)||'').trim()])) as Record<Field,string>;const err:Partial<Record<Field,string>>={};if(!fields.name)err.name=t.errors.name;if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fields.email))err.email=t.errors.email;if(!fields.subject)err.subject=t.errors.subject;if(fields.message.length<10)err.message=t.errors.message;setErrors(err);setFeedback('');if(Object.keys(err).length){setDraft(null);form.current?.querySelector<HTMLInputElement>(`[name="${Object.keys(err)[0]}"]`)?.focus();return;}const body=`${fields.message}\n\n${t.nameLabel}: ${fields.name}\n${t.emailField}: ${fields.email}`;setDraft({href:`mailto:${contact.email}?subject=${encodeURIComponent(fields.subject.replace(/[\r\n]/g,' '))}&body=${encodeURIComponent(body)}`,body:`${fields.subject}\n\n${body}`});}
 const fields:[Field,string,string][]=[['name',t.nameLabel,t.namePlaceholder],['email',t.emailField,t.emailPlaceholder],['subject',t.subject,t.subjectPlaceholder],['message',t.message,t.messagePlaceholder]];
 return <div className='contact-form-wrap'><h2>{t.formTitle}</h2><p className='form-note' id='form-note'>{t.formNote}</p><form ref={form} noValidate onSubmit={submit} aria-describedby='form-note' onChange={()=>{if(draft)setDraft(null);setFeedback('');}}><div className='form-grid'>{fields.map(([key,label,placeholder])=><div className={`form-field field-${key}`} key={key}><label htmlFor={key}>{label}<span aria-hidden='true'> *</span></label>{key==='message'?<textarea id={key} name={key} placeholder={placeholder} rows={5} required maxLength={4000} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>:<input id={key} name={key} type={key==='email'?'email':'text'} autoComplete={key==='name'?'name':key==='email'?'email':'off'} dir={key==='email'?'ltr':undefined} placeholder={placeholder} required maxLength={key==='subject'?160:200} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>} {errors[key]&&<p id={`${key}-error`} className='field-error'>{errors[key]}</p>}</div>)}</div><button type='submit' className='button'>{t.send}<ArrowUpRight size={19} className='flow-arrow'/></button><div className='form-feedback' aria-live='polite'>{draft&&<div className='draft-ready'><p>{t.formReady}</p><div className='draft-actions'><a className='text-link' href={draft.href}>{t.openEmail}<ArrowUpRight size={17}/></a><button className='text-link' type='button' onClick={async()=>{try{await navigator.clipboard.writeText(draft.body);setFeedback(t.copied);}catch{setFeedback(t.copyError);}}}>{t.copyMessage}<Copy size={16}/></button></div></div>}{feedback&&<p>{feedback}</p>}</div></form></div>;
}
