import Link from 'next/link';
import {ArrowUpRight,ArrowRight,ArrowDown,Download,Mail,Phone,MapPin} from 'lucide-react';
import {copy,contact,type Lang} from '@/content/translations';
import {projects,type Project} from '@/content/projects';
import {ArtworkImage} from './artwork';
import {routeFor} from '@/content/routes';
import {Gallery} from './gallery';
import {ContactForm} from './contact-form';
export function Eyebrow({children,number}:{children:React.ReactNode;number?:string}){return <p className='eyebrow'>{number&&<span className='section-number'>{number}</span>}{children}</p>;}
function Cover({project,priority=false}:{project:Project;priority?:boolean}){return <div className={`project-cover cover-${project.theme}`}><ArtworkImage asset={project.cover} alt={project.name.en} priority={priority}/>{project.theme==='prime'&&<ArtworkImage asset='prime-lifestyle' alt='PRIME HAVEN'/>}</div>;}
export function ProjectCard({project,lang,index}:{project:Project;lang:Lang;index:number}){
 const t=copy[lang];return <article className={`project-card card-${project.theme}`}><Link href={routeFor(lang,`work/${project.slug}`)} className='project-card-link' aria-label={`${t.project}: ${project.name[lang]}`}><Cover project={project}/><div className='project-caption'><div><p>{project.category[lang]}</p><h3>{project.name[lang]}</h3></div><span className='round-arrow'><ArrowUpRight className='flow-arrow' strokeWidth={1.4}/></span></div></Link><span className='project-number'>{String(index+1).padStart(2,'0')}</span></article>;
}
function ProjectGrid({lang,home=false}:{lang:Lang;home?:boolean}){const data=home?[projects[0],projects[1],projects[2],projects[4]]:projects;return <div className={`work-grid ${home?'home-work-grid':''}`}>{data.map((project,i)=><ProjectCard project={project} lang={lang} index={i} key={project.slug}/>)}</div>;}
export function HomePage({lang}:{lang:Lang}){
 const t=copy[lang];return <><section className='hero shell'><div className='hero-main'><Eyebrow>{t.name} <span className='eyebrow-divider'/> {t.title}</Eyebrow><h1>{t.hero1}<br/><em>{t.hero2}</em></h1><div className='hero-intro'><p>{t.intro}</p><div className='hero-ctas'><Link className='button' href={routeFor(lang,'work')}>{t.viewWork}<ArrowUpRight size={20} className='flow-arrow'/></Link><Link className='text-link' href={routeFor(lang,'contact')}>{t.contactMe}<ArrowUpRight size={18} className='flow-arrow'/></Link></div></div></div><div className='hero-identity'><div className='identity-note'><span>{t.heroTop}</span><span className='mini-cross' aria-hidden='true'>+</span></div><div className='hero-logo-panel'><img src='/assets/ma-logo.webp' alt={`${t.name} — MA`} width='1392' height='860' fetchPriority='high'/></div><div className='identity-bottom'><span>{t.disciplines}</span><span className='color-samples' aria-hidden='true'><i/><i/></span></div></div><div className='hero-baseline'><span>{t.based}</span><span>{t.available}</span><a href='#selected-work' aria-label={t.selected}><ArrowDown size={19}/></a></div></section><section className='work-section shell' id='selected-work'><div className='section-top'><div><Eyebrow number='01'>{t.selected}</Eyebrow><h2>{t.nav.work}<span className='title-period'>.</span></h2></div><Link href={routeFor(lang,'work')} className='text-link'>{t.allWork}<ArrowUpRight className='flow-arrow' size={19}/></Link></div><ProjectGrid lang={lang} home/></section><section className='home-about'><div className='shell about-split'><div><Eyebrow number='02'>{t.aboutLabel}</Eyebrow><h2>{t.aboutHeadline}</h2></div><div><p className='lead'>{t.aboutIntro}</p><p>{t.aboutText}</p><Link href={routeFor(lang,'about')} className='text-link'>{t.aboutLink}<ArrowUpRight size={19} className='flow-arrow'/></Link></div></div></section><section className='home-services shell'><div><Eyebrow number='03'>{t.serviceLabel}</Eyebrow><h2>{t.serviceHeading}</h2><Link className='text-link' href={routeFor(lang,'services')}>{t.nav.services}<ArrowUpRight size={19} className='flow-arrow'/></Link></div><div className='service-mini-list'>{t.services.map((s,i)=><Link key={s.title} href={routeFor(lang,'services')}><span>0{i+1}</span><h3>{s.title}</h3><ArrowUpRight size={21} className='flow-arrow'/></Link>)}</div></section></>;
}
function PageHeading({label,title,intro,number='01'}:{label:string;title:string;intro?:string;number?:string}){return <div className='page-heading'><Eyebrow number={number}>{label}</Eyebrow><h1>{title}</h1>{intro&&<p>{intro}</p>}</div>;}
export function WorkPage({lang}:{lang:Lang}){const t=copy[lang];return <section className='shell page-section work-page'><PageHeading label={t.selected} title={t.nav.work+'.'} intro={t.workIntro}/><ProjectGrid lang={lang}/></section>;}
const software=['Adobe Photoshop','Adobe Illustrator','Adobe InDesign','Adobe Lightroom','Canva'];
export function Education({lang}:{lang:Lang}){const t=copy[lang];return <section className='education-section'><Eyebrow>{t.education}</Eyebrow><div className='education-row'><span dir='ltr'>2022 — 2026</span><div><h3>{t.university}</h3><p>{t.degree}</p><small>{lang==='ar'?'كوجالي، تركيا':'Kocaeli, Türkiye'}</small></div></div><div className='education-row'><span dir='ltr'>2021 — 2022</span><div><h3>{t.languageSchool}</h3><p>{t.certificate}</p><small>{lang==='ar'?'كوجالي، تركيا':'Kocaeli, Türkiye'}</small></div></div></section>;}
export function AboutPage({lang}:{lang:Lang}){
 const t=copy[lang];return <><section className='shell page-section'><PageHeading label={t.aboutLabel} title={t.aboutHeadline}/><div className='about-main'><div className='about-identity'><img src='/assets/ma-logo.webp' width='1392' height='860' alt={`${t.name} — MA`}/><div><h2>{t.name}</h2><span>{t.title}</span></div></div><div className='about-story'><p className='lead'>{t.aboutIntro}</p><p>{t.aboutText}</p><div className='experience-number'><strong dir='ltr'>4+</strong><span>{t.years}</span></div><a className='button' href='/Mohammed-Amin-CV.pdf' download>{t.download}<Download size={18}/></a><span className='download-note'>{t.cvLanguage}</span></div></div><div className='about-detail-grid'><Education lang={lang}/><section><Eyebrow>{t.spoken}</Eyebrow><ul className='language-list'>{t.languageLevels.map(s=><li key={s}>{s}</li>)}</ul></section></div></section><section className='tool-section'><div className='shell'><Eyebrow>{t.tools}</Eyebrow><div className='tool-list'>{software.map((s,i)=><div key={s}><span>{['Ps','Ai','Id','Lr','C'][i]}</span><p dir='ltr'>{s}</p></div>)}</div></div></section></>;
}
export function ServicesPage({lang}:{lang:Lang}){const t=copy[lang];return <section className='shell page-section services-page'><PageHeading label={t.serviceLabel} title={t.serviceHeading} intro={t.serviceIntro}/><div className='services-list'>{t.services.map((s,i)=><article key={s.title}><span className='service-number'>0{i+1}</span><div><h2>{s.title}</h2><p className='service-tags'>{s.tags}</p></div><p>{s.text}</p></article>)}</div><div className='service-example'><ArtworkImage asset='athar-bag' alt={projects[0].gallery[2].caption[lang]}/><div><Eyebrow>{t.selected}</Eyebrow><h2>ATHAR PERFUMES</h2><p>{projects[0].overview[lang]}</p><Link href={routeFor(lang,'work/athar-perfumes')} className='text-link'>{t.project}<ArrowUpRight size={19} className='flow-arrow'/></Link></div></div></section>;}
export function ExperiencePage({lang}:{lang:Lang}){
 const t=copy[lang];const jobs=[{year:`2020 — ${t.present}`,title:t.freelance,company:null},{year:'2024 — 2025',title:t.title,company:'Troy 41 Real Estate'},{year:'2024',title:t.title,company:'New Yemen Media Center'},{year:'2021',title:t.media,company:t.union},{year:'2018 — 2020',title:t.title,company:'Lamsat Ibda’a'}];
 return <section className='shell page-section experience-page'><PageHeading label={t.experienceLabel} title={t.experienceHeading} intro={t.experienceIntro}/><div className='timeline'>{jobs.map((j,i)=><article key={j.year}><div className='timeline-date'><span>{j.year}</span></div><div><h2>{j.title}</h2>{j.company&&<h3>{j.company}</h3>}<p>{t.jobs[i]}</p></div></article>)}</div><div className='experience-end'><Education lang={lang}/><div className='cv-panel'><Download size={32} strokeWidth={1.2}/><h2>{t.name}</h2><p>{t.title}</p><a className='button' href='/Mohammed-Amin-CV.pdf' download>{t.download}<Download size={17}/></a><small>{t.cvLanguage}</small></div></div></section>;
}
export function ContactPage({lang}:{lang:Lang}){const t=copy[lang];return <section className='shell page-section contact-page'><PageHeading label={t.nav.contact} title={t.contactHeading} intro={t.contactIntro}/><div className='contact-grid'><div className='contact-details'><div><Mail size={20}/><span>{t.emailLabel}</span><a href={`mailto:${contact.email}`} dir='ltr'>{contact.email}</a></div><div><Phone size={20}/><span>{t.phoneLabel}</span><a href={`tel:${contact.tel}`} dir='ltr'>{contact.phone}</a></div><div><MapPin size={20}/><span>{t.location}</span><p>{lang==='ar'?'إزميت، كوجالي، تركيا':contact.location}</p></div><a className='text-link' href={contact.linkedin} target='_blank' rel='noopener noreferrer'>{t.connect}<ArrowUpRight size={19}/></a></div><ContactForm lang={lang}/></div></section>;}
export function ProjectPage({lang,project}:{lang:Lang;project:Project}){
 const t=copy[lang],next=projects[(projects.indexOf(project)+1)%projects.length];
 return <article className={`case-study case-${project.theme}`}><div className='shell case-heading'><Link className='text-link back-link' href={routeFor(lang,'work')}><ArrowRight className='back-arrow' size={18}/>{t.backWork}</Link><div className='case-title-row'><h1>{project.name[lang]}</h1><p>{project.category[lang]}</p></div></div><div className='shell case-cover'><Cover project={project} priority/></div><section className='shell case-info'><div><Eyebrow>{t.overview}</Eyebrow><p className='lead'>{project.overview[lang]}</p><div className='case-direction'><h2>{t.direction}</h2><p>{project.direction[lang]}</p></div></div><aside><div><h2>{t.industry}</h2><p>{project.industry[lang]}</p></div><div><h2>{t.scope}</h2><ul>{project.scope[lang].map(s=><li key={s}>{s}</li>)}</ul></div></aside></section><section className='shell case-gallery-section'><div className='section-top'><Eyebrow>{t.gallery}</Eyebrow><span className='secondary-number'>01 — {String(project.gallery.length).padStart(2,'0')}</span></div><Gallery items={project.gallery} lang={lang} name={project.name[lang]} theme={project.theme}/></section><section className='next-project shell'><Eyebrow>{t.nextProject}</Eyebrow><Link href={routeFor(lang,`work/${next.slug}`)}><h2>{next.name[lang]}</h2><ArrowUpRight className='flow-arrow' strokeWidth={1}/></Link></section></article>;
}
export function NotFoundPage({lang}:{lang:Lang}){const t=copy[lang];return <section className='shell error-page'><span className='error-number'>404</span><h1>{t.notFound}</h1><p>{t.notFoundText}</p><Link className='button' href={routeFor(lang)}>{t.backHome}<ArrowUpRight size={19} className='flow-arrow'/></Link></section>;}
